artifact_location: file:///c:/Code/GenAIGroupProject/development/mlflow_agent_development/0
creation_time: 1717080571702
experiment_id: '0'
last_update_time: 1717080571702
lifecycle_stage: active
name: Default
