channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=22.3
- pip:
  - mlflow==2.13.0
  - click==8.1.7
  - cloudpickle==3.0.0
  - langchain==0.1.20
  - numpy==1.26.4
  - openai==1.30.4
  - packaging==23.2
  - psutil==5.9.8
  - pydantic==2.7.1
  - pygments==2.18.0
  - pyyaml==6.0.1
  - requests==2.32.2
  - tornado==6.4
name: mlflow-env
